#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Formatting, styling and building your project before committing changes'

npx lint-staged ||
(
  echo '🤢🤮🤢🤮 Linters Check Failed. 🤢🤮🤢🤮
    Run npm run lint or npm run pretty to check what went wrong.';
  false;
)

echo '🤔🤔🤔🤔 Code looks good. Trying to build project now. 🤔🤔🤔🤔'

npm run build ||
(
  echo '❌👷🔨❌ Build Failed. ❌👷🔨❌
    Build failed: View the errors above to see why.'
  false;
)

echo '✅✅✅✅ Winner winner chicken dinner. I am committing changes now. ✅✅✅✅'
